// Generated by CoffeeScript 1.8.0
(function() {
  Ext.define('GSW.view.map.GoogleMapPanel', {
    extend: 'Ext.panel.Panel',
    id: 'gmap-panel',
    requires: ["Ext.ux.GMapPanel"],
    xtype: 'google-map-panel',
    width: '100%',
    height: '100%',
    layout: 'fit',
    constructor: function(config) {
      this.callParent(config);
      return this;
    },
    listeners: {
      afterrender: (function(_this) {
        return function(panel) {
          return panel.drawMap();
        };
      })(this)
    },
    drawMap: function() {
      var map, opts;
      opts = {
        zoom: 8,
        mapTypeId: google.maps.MapTypeId.ROADMAP,
        center: new google.maps.LatLng(35.0117, 135.7683),
        mapTypeId: google.maps.MapTypeId.ROADMAP
      };
      return map = new google.maps.Map(document.getElementById("gmap-panel"), opts);
    }
  });

}).call(this);
