// Generated by CoffeeScript 1.8.0
(function() {
  Ext.define('GSW.store.ImageStore', {
    extend: 'Ext.data.Store',
    model: 'GSW.model.Image',
    proxy: {
      type: 'memory'
    },
    constructor: function() {
      this.listenTogetherJS();
      return this.callParent(arguments);
    },
    listenTogetherJS: function() {
      console.log("start listenening");
      return TogetherJS.hub.on("update:image", (function(_this) {
        return function(data) {
          var image, k, v, _ref;
          image = _this.getById(data.id);
          console.log(image);
          if (image) {
            _ref = data["attrs"];
            for (k in _ref) {
              v = _ref[k];
              image.set(k, v);
            }
            return image.fireEvent("update:image");
          }
        };
      })(this));
    }
  });

}).call(this);
