// Generated by CoffeeScript 1.8.0
(function() {
  Ext.define('GSW.store.RegionStore', {
    extend: 'Ext.data.Store',
    model: 'GSW.model.Region',
    proxy: {
      type: 'memory'
    },
    constructor: function() {
      this.listenTogetherJS();
      return this.callParent(arguments);
    },
    listenTogetherJS: function() {
      TogetherJS.hub.on("update:region", (function(_this) {
        return function(data) {
          var k, region, v, _ref;
          region = _this.getById(data.id);
          console.log(region);
          if (region) {
            _ref = data["attrs"];
            for (k in _ref) {
              v = _ref[k];
              region.set(k, v);
            }
            return region.fireEvent("update:region");
          }
        };
      })(this));
      return TogetherJS.hub.on("create:region", (function(_this) {
        return function(data) {
          var image, image_id, region, user, user_id;
          region = new GSW.model.Region(data.attrs);
          region.id = data.attrs.id;
          _this.add(region);
          image_id = region.get('image_id');
          image = Ext.getStore("GSW.store.ImageStore").getById(image_id);
          image.regions().add(region);
          user_id = region.get('user_id');
          user = Ext.getStore("GSW.store.UserStore").getById(user_id);
          region.setUser(user);
          console.log("new region added", region.getImage());
          return image.fireEvent("create:region", region);
        };
      })(this));
    }
  });

}).call(this);
