// Generated by CoffeeScript 1.8.0
(function() {
  var convert2Div, init;

  init = function(callback) {
    return Tabletop.init({
      key: '1CZrYzD1s41hJBaMiEvBXM2oAR-5pe-zpGIW6KjyH8xE',
      simpleSheet: true,
      callback: function(data, tabletop) {
        return callback(data);
      }
    });
  };

  convert2Div = function(text) {
    return text.replace(/([一-龠]*)（([ぁ-んァ-ヶゝ]+)）/g, function(match, kanji, ruby) {
      return "<ruby>\n  <rb>" + kanji + "</rb>\n  <rt>" + ruby + "</rt>            \n</ruby>";
    });
  };

  init(function(data) {
    var d, div, line, text, _i, _len, _results;
    div = $("#transcription");
    console.log(data);
    _results = [];
    for (_i = 0, _len = data.length; _i < _len; _i++) {
      d = data[_i];
      text = convert2Div(d['翻刻文']);
      line = $("<div>" + text + "</div>");
      _results.push(div.append(line));
    }
    return _results;
  });

}).call(this);
