// Generated by CoffeeScript 1.8.0
(function() {
  Ext.define('GSW.view.transcription.ContextMenu', {
    extend: 'Ext.menu.Menu',
    constructor: function(config) {
      this.callParent(config);
      if (!(this.editor = config.editor)) {
        return Ext.Error.raise("editor not given");
      }
    },
    items: [
      {
        text: 'Edit TEI attributes'
      }, {
        text: 'Delete markup'
      }, '-', {
        text: 'Edit annotation'
      }, {
        text: 'Remove annotation'
      }
    ]
  });

}).call(this);
