// Generated by CoffeeScript 1.7.1
(function() {
  Ext.define('GSW.view.transcription.SourcePanel', {
    extend: 'Ext.panel.Panel',
    xtype: "tei-source-panel",
    padding: 5,
    constructor: function(config) {
      this.callParent(arguments);
      if (!config.title) {
        Ext.Error.raise({
          msg: "title not given"
        });
      }
      return this.setTitle(config.title);
    },
    setSource: function(src) {
      return this.setHtml(src);
    }
  });

}).call(this);
