// Generated by CoffeeScript 1.7.1
(function() {
  Ext.define('GSW.view.transcription.TeiPanel', {
    extend: 'Ext.panel.Panel',
    xtype: "tei-panel",
    bodyBorder: false,
    layout: 'fit',
    padding: 0
  });

}).call(this);
