// Generated by CoffeeScript 1.7.1
(function() {
  Ext.define('GSW.view.transcription.TranscriptionController', {
    extend: 'Ext.app.Controller',
    models: ['Zone'],
    refs: [
      {
        ref: 'canvas-panel'
      }
    ]
  });

}).call(this);
