// Generated by CoffeeScript 1.7.1
(function() {
  var SourceDocCanvas, Surface, Zone,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  window.canvas = SourceDocCanvas;

  Surface = (function() {
    function Surface(imgURL, config) {
      if (config == null) {
        config = {};
      }
    }

    return Surface;

  })();

  Zone = (function(_super) {
    __extends(Zone, _super);

    function Zone() {
      Zone.__super__.constructor.call(this);
    }

    return Zone;

  })(fabric.Rect);

  window.Zone = Zone;

  SourceDocCanvas = (function() {
    function SourceDocCanvas(canvasId, config) {
      var rect;
      if (config == null) {
        config = {};
      }
      this.c = new fabric.CanvasWithViewport(canvasId);
      this.bindEventListeners();
      this.setBackgroundImg("http://www.ancestorsremembered.com/Capt%20Dave/hannah_handwriting.jpg");
      rect = new fabric.Rect({
        width: 50,
        height: 50,
        left: 50,
        top: 50,
        strokeWidth: 1,
        stroke: 'red',
        fill: "rgba(0,0,0,0)"
      });
      this.c.add(rect);
    }

    return SourceDocCanvas;

  })();

  window.SourceDocCanvas = SourceDocCanvas;

}).call(this);
