// Generated by CoffeeScript 1.8.0
(function() {
  Ext.define('GSW.model.Base', {
    extend: 'Ext.data.Model',
    schema: {
      namespace: 'GSW.model'
    },
    on: function(event, callback) {
      if (!this.handler) {
        this.handler = {};
      }
      this.handler[event] = this.handler[event] || [];
      return this.handler[event].push(callback);
    },
    fireEvent: function(event) {
      var callback, _i, _len, _ref, _results;
      if (!this.handler) {
        return;
      }
      if (!this.handler[event]) {
        return;
      }
      _ref = this.handler[event];
      _results = [];
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        callback = _ref[_i];
        _results.push(callback());
      }
      return _results;
    }
  });

}).call(this);
