// Generated by CoffeeScript 1.8.0
(function() {
  Ext.define('GSW.model.Image', {
    extend: 'GSW.model.Base',
    fields: [
      {
        name: 'title',
        type: 'string',
        defaultValue: ''
      }, {
        name: 'url',
        type: 'string',
        defaultValue: ''
      }, {
        name: 'url_thumbnail',
        type: 'string',
        defaultValue: ''
      }, {
        name: 'transcription',
        type: 'string',
        defaultValue: ''
      }, {
        name: 'translation',
        type: 'string',
        defaultValue: ''
      }, {
        name: 'notes',
        type: 'string',
        defaultValue: ''
      }
    ],
    notifyRemote: function(attribute) {
      var remoteURL, url;
      remoteURL = GSW.app.getServerURL();
      url = remoteURL + "images/" + this.get('id');
      return Ext.Ajax.request({
        method: 'PUT',
        withCredentials: true,
        url: url,
        success: function(data) {
          return console.log(data);
        }
      });
    },
    statics: {
      fromJSON: function(data) {
        var config;
        config = {
          id: data._id.$oid,
          title: data.title,
          url: data.image_data.url,
          url_thumbnail: data.image_data.thumbnail.url,
          transcription: data.transcription || '',
          translation: data.translation || '',
          notes: data.note || ''
        };
        return new this(config);
      }
    }
  });

}).call(this);
