// Generated by CoffeeScript 1.8.0
(function() {
  Ext.define('GSW.model.Manuscript', {
    extend: 'GSW.model.Base',
    fields: [
      {
        name: 'title',
        type: 'string',
        defaultValue: ''
      }, {
        name: 'description',
        type: 'string',
        defaultValue: ''
      }, {
        name: 'projectId',
        reference: 'Project'
      }
    ],
    statics: {
      fromJSON: function(data) {
        var config, images, img, m, parent;
        images = data.images ? (function() {
          var _i, _len, _ref, _results;
          _ref = data.images;
          _results = [];
          for (_i = 0, _len = _ref.length; _i < _len; _i++) {
            img = _ref[_i];
            _results.push(GSW.model.Image.fromJSON(img));
          }
          return _results;
        })() : [];
        config = {
          id: data._id.$oid,
          title: data.title,
          description: data.description
        };
        m = new this(config);
        parent = m.images();
        parent.add(images);
        Ext.getStore('GSW.store.ManuscriptStore').add(m);
        return m;
      }
    }
  });

}).call(this);
