// Generated by CoffeeScript 1.8.0
(function() {
  Ext.define('GSW.model.Manuscript', {
    extend: 'GSW.model.Base',
    fields: [
      {
        name: 'title',
        type: 'string',
        defaultValue: ''
      }, {
        name: 'description',
        type: 'string',
        defaultValue: ''
      }
    ],
    hasMay: [
      {
        name: 'images',
        model: 'GSW.model.Image'
      }
    ],
    statics: {
      fromJSON: function(data) {
        var config, img;
        config = {
          id: data._id.$oid,
          title: data.title,
          description: data.description,
          images: (function() {
            var _i, _len, _ref, _results;
            _ref = data.images;
            _results = [];
            for (_i = 0, _len = _ref.length; _i < _len; _i++) {
              img = _ref[_i];
              _results.push(GSW.model.Image.fromJSON(img));
            }
            return _results;
          })()
        };
        return new this(config);
      }
    }
  });

}).call(this);
