// Generated by CoffeeScript 1.8.0
(function() {
  Ext.define('GSW.model.Surface', {
    extend: 'GSW.model.Base',
    fields: [
      {
        name: 'imageURI',
        type: 'string',
        defaultValue: ''
      }, {
        name: 'annotations',
        defaultValue: []
      }
    ],
    hasMany: 'Zone',
    hasMany: 'ImageAnnotation',
    getImageURI: function() {
      return "http://dummy_image.org";
    }
  });

}).call(this);
