// Generated by CoffeeScript 1.7.1
(function() {
  Ext.define('GSW.util.XmlFormatter', {
    singleton: true,
    format: function(src) {
      var beautified, highlighted, l, lines, spaceCnt;
      window.hljs.configure({
        tabReplace: true,
        useBR: true
      });
      beautified = window.vkbeautify.xml(src);
      highlighted = window.hljs.highlight("xml", beautified).value;
      lines = (function() {
        var _i, _len, _ref, _results;
        _ref = highlighted.split("\n");
        _results = [];
        for (_i = 0, _len = _ref.length; _i < _len; _i++) {
          l = _ref[_i];
          spaceCnt = l.indexOf('<');
          _results.push(l = ("<span style='padding-left: " + (spaceCnt * 5) + "px'></span>") + l);
        }
        return _results;
      })();
      return lines.join('<br/>');
    }
  });

}).call(this);
