// Generated by CoffeeScript 1.8.0
(function() {
  Ext.define('GSW.view.transcription.state.DrawingState', {
    extend: 'GSW.view.transcription.state.DefaultState',
    requires: ['GSW.model.Zone'],
    onSwitchState: function() {
      this.drawMode = false;
      this.origin = null;
      return this.zone = null;
    },
    mousedown: function(event) {
      var zoneModel;
      if (!this.drawMode) {
        this.drawMode = true;
        this.origin = this.canvas.c.getPointer(event.e);
        zoneModel = Ext.create('GSW.model.Zone');
        this.zone = new fabric.Zone({
          width: 0,
          height: 0,
          left: this.origin.x,
          top: this.origin.y,
          canvas: this.canvas.c,
          model: zoneModel
        });
        this.canvas.c.add(this.zone);
        this.canvas.c.renderAll();
        return this.canvas.c.setActiveObject(this.zone);
      }
    },
    mousemove: function(event) {
      var h, mouse, w;
      if (this.drawMode) {
        mouse = this.canvas.c.getPointer(event.e);
        w = Math.abs(mouse.x - this.origin.x);
        h = Math.abs(mouse.y - this.origin.y);
        this.zone.set("width", w).set("height", h);
        return this.canvas.c.renderAll();
      }
    },
    mouseout: function(event) {
      return this._onZoneCreated(event);
    },
    mouseup: function(event) {
      return this._onZoneCreated(event);
    },
    _onZoneCreated: function(event) {
      var _ref;
      if ((_ref = this.zone) != null) {
        _ref.updateModel();
      }
      this.drowMode = false;
      this.zone = null;
      return this.canvas.resetState();
    }
  });

}).call(this);
