// Generated by CoffeeScript 1.8.0
(function() {
  Ext.define('GSW.view.transcription.state.ImageSelectionState', {
    extend: 'GSW.view.transcription.state.DefaultState',
    requires: ['GSW.model.ImageAnnotation', 'GSW.view.transcription.ImageAnnotationPanel', 'GSW.view.transcription.menu.CanvasContextMenu'],
    Onswitchstate: function() {
      this.drawMode = false;
      this.origin = null;
      return this.region = null;
    },
    mousedown: function(event) {
      var options;
      if (!this.drawMode) {
        this.drawMode = true;
        this.origin = this.canvas.c.getPointer(event.e);
        options = {
          width: 0,
          height: 0,
          left: this.origin.x,
          top: this.origin.y,
          canvas: this.canvas.c
        };
        this.region = new fabric.Region(options);
        this.canvas.c.add(this.region);
        this.canvas.c.renderAll();
        return console.log(this.region);
      }
    },
    mousemove: function(event) {
      var h, mouse, w;
      if (this.drawMode) {
        mouse = this.canvas.c.getPointer(event.e);
        w = Math.abs(mouse.x - this.origin.x);
        h = Math.abs(mouse.y - this.origin.y);
        this.region.set("width", w).set("height", h);
        return this.canvas.c.renderAll();
      }
    },
    mouseout: function(event) {
      return this._onZoneCreated(event);
    },
    mouseup: function(event) {
      return this._onZoneCreated(event);
    },
    _onZoneCreated: function(event) {
      this.drawMode = false;
      console.log(this.region.get('left'), this.region.get('top'), this.region.get('width'), this.region.get('height'));
      this._createRegionModel(this.region);
      this.region = null;
      this._showMenu(event);
      return this.canvas.resetState();
    },
    _showMenu: function(event) {
      var menu;
      menu = Ext.create("GSW.view.transcription.menu.CanvasContextMenu", {
        canvas: this.canvas
      });
      return menu.showAt(event.e.clientX, event.e.clientY);
    },
    _createRegionModel: function(region) {
      var config, model;
      config = {
        x: Math.ceil(region.get('left')),
        y: Math.ceil(region.get('top')),
        w: Math.ceil(region.get('width')),
        h: Math.ceil(region.get('height')),
        image: this.canvas.getImageModel()
      };
      model = GSW.model.Region.create(config);
      return model;
    }
  });

}).call(this);
