// Generated by CoffeeScript 1.7.1
(function() {
  Ext.define('GSW.view.transcription.form.AbstractMarkupForm', {
    extend: 'Ext.form.Panel',
    requires: ['Ext.form.FieldSet'],
    xtype: 'abstract-markup-form',
    frame: true,
    title: 'マークアップ',
    autoScroll: true,
    width: 355,
    floating: true,
    closable: true,
    fieldDefaults: {
      labelAlign: 'right',
      labelWidth: 115,
      msgTarget: 'side'
    },
    buttons: [
      {
        text: '登録',
        handler: (function(_this) {
          return function(btn) {
            return btn.up('form').register();
          };
        })(this)
      }, {
        text: 'キャンセル',
        handler: (function(_this) {
          return function(btn) {
            return btn.up('form').cancel();
          };
        })(this)
      }
    ],
    constructor: function(config) {
      this.callParent(arguments);
      if (!(this.editor = config.editor)) {
        return Ext.Error.raise("editor not given");
      }
    },
    cancel: function() {
      return this.close();
    },
    notifySelectionError: function() {
      return Ext.Msg.alert('エラー', 'マークアップ位置が不正です');
    }
  });

}).call(this);
