// Generated by CoffeeScript 1.8.0
(function() {
  Ext.define('GSW.view.transcription.form.AbstractMarkupForm', {
    extend: 'Ext.form.Panel',
    requires: ['Ext.form.FieldSet'],
    xtype: 'abstract-markup-form',
    frame: true,
    title: 'Markup',
    modal: true,
    autoScroll: true,
    width: 400,
    bodyPadding: 10,
    floating: true,
    closable: true,
    layout: 'form',
    fieldDefaults: {
      labelAlign: 'left',
      labelWidth: 115,
      msgTarget: 'side'
    },
    buttons: [
      {
        text: 'Markup',
        handler: (function(_this) {
          return function(btn) {
            return btn.up('form').register();
          };
        })(this)
      }, {
        text: 'Cancel',
        handler: (function(_this) {
          return function(btn) {
            return btn.up('form').cancel();
          };
        })(this)
      }
    ],
    constructor: function(config) {
      this.callParent(arguments);
      if (!(this.editor = config.editor)) {
        return Ext.Error.raise("editor not given");
      }
    },
    cancel: function() {
      return this.close();
    },
    notifySelectionError: function() {
      return Ext.Msg.alert('Error', 'Invalid markup position');
    }
  });

}).call(this);
