// Generated by CoffeeScript 1.8.0
(function() {
  Ext.define('GSW.view.transcription.form.ImageAnnotationForm', {
    extend: 'Ext.form.Panel',
    requires: ['Ext.layout.container.Form'],
    xtype: 'image-annotation-form',
    title: 'Annotate image',
    frame: true,
    modal: true,
    autoScroll: true,
    bodyPadding: 10,
    width: 400,
    floating: true,
    closable: false,
    layout: 'form',
    fieldDefaults: {
      labelAlign: 'left',
      msgTarget: 'side'
    },
    constructor: function(config) {
      var anno;
      this.callParent(config);
      this.model = config.model;
      this.down('image').setSrc(this.model.crop());
      anno = this.model.get('annotation');
      if (anno && anno !== '') {
        this.down('textareafield').setText(anno);
      }
      return this;
    },
    items: [
      {
        xtype: 'image',
        fieldLabel: 'Image',
        height: 200
      }, {
        xtype: 'textareafield',
        allowBlank: false,
        grow: true,
        fieldLabel: 'Text',
        width: '100%',
        name: 'annotation',
        emptyText: 'Put some comments. You can use hashtags like this: #kyoto'
      }
    ],
    buttons: [
      {
        text: 'Add',
        handler: (function(_this) {
          return function(btn) {
            return btn.up('form').register();
          };
        })(this)
      }, {
        text: 'Cancel',
        handler: (function(_this) {
          return function(btn) {
            return btn.up('form').cancel();
          };
        })(this)
      }
    ],
    register: function() {
      this.model.set("annotation", this.getValues().annotation);
      this.model.createOnServer((function(_this) {
        return function() {
          return _this.model.notifyCreation();
        };
      })(this));
      return this.close();
    },
    cancel: function() {
      this.model.view.canvas.remove(this.model.view);
      this.model.erase();
      return this.close();
    }
  });

}).call(this);
