// Generated by CoffeeScript 1.8.0
(function() {
  Ext.define('GSW.view.transcription.form.RubyForm', {
    extend: 'GSW.view.transcription.form.AbstractMarkupForm',
    xtype: 'ruby-form',
    title: 'Add ruby to text',
    modal: true,
    items: [
      {
        xtype: 'textfield',
        allowBlank: false,
        fieldLabel: 'Ruby characters',
        name: 'text',
        emptyText: 'るび'
      }
    ],
    register: function() {
      var e;
      try {
        return this.editor.ruby(this.getValues().text);
      } catch (_error) {
        e = _error;
        return this.notifySelectionError();
      } finally {
        this.close();
      }
    }
  });

}).call(this);
