// Generated by CoffeeScript 1.8.0
(function() {
  Ext.define('GSW.view.transcription.menu.CanvasContextMenu', {
    xtype: 'canvas-context-menu',
    extend: 'Ext.menu.Menu',
    constructor: function(config) {
      this.callParent(config);
      if (!(this.canvas = config.canvas)) {
        return Ext.Error.raise("editor not given");
      }
    },
    items: [
      {
        text: 'Annotate'
      }, {
        text: 'Add to dictionary'
      }, {
        text: 'Search'
      }, '-', {
        text: 'Cancel'
      }
    ]
  });

}).call(this);
